### ISSUE TITLE
System hard locking when trying to download anything

### ISSUE THREAD

**Issue by ChronosWing** [V10lator/NUSspli#22]
I’m trying the latest version that was just posted but when I try to download any title it makes it a few files in then the entire wiiU hard locks requiring hard reset. 

![image](https://user-images.githubusercontent.com/82796286/115186148-2bd48100-a0af-11eb-9322-d33a744eb2b6.jpg)

**Comment by V10lator** [comment]
Should be fixed with v1.19.

**Comment by ChronosWing** [comment]
Still not fixed, hard locking either at creating very or when during file download. 

![Uploading image.jpg…]()

**Comment by V10lator** [comment]
Can't recreate. Could you please make double-sure you're using version 1.19? If so could you use FTPiiU Everywhere to delete all files at `/storage_slc/logs/`, then recreate the issue, then handle the file `/storage_slc/logs/1.log` to me?

**Comment by homebrewGT** [comment]
Having the same issue, happens not long after starting the download, my scenario:

I am downloading to SD and installing to NAND, download starts and then after a few files, error with annoying beep. Forcing me to shutdown.

Version 1.9 with the new environment

**Comment by ChronosWing** [comment]
> Can't recreate. Could you please make double-sure you're using version 1.19? If so could you use FTPiiU Everywhere to delete all files at `/storage_slc/logs/`, then recreate the issue, then handle the file `/storage_slc/logs/1.log` to me?
> 
> //EDIT: Also a udp log could help. For that have https://github.com/dimok789/loadiine_gx2/blob/master/udp_debug_reader/UdpDebugReader.exe running on your PC while running the DEBUG version of NUSspli on the Wii U. Make sure both are on the same network.

[1.log](https://github.com/V10lator/NUSspli/files/6345876/1.log)

Done, I was unable to get UdpDebugReader to work, it just kept creating blank log files.

**Comment by ChronosWing** [comment]
> Can't recreate. Could you please make double-sure you're using version 1.19? If so could you use FTPiiU Everywhere to delete all files at `/storage_slc/logs/`, then recreate the issue, then handle the file `/storage_slc/logs/1.log` to me?
> 
> //EDIT: Also a udp log could help. For that have https://github.com/dimok789/loadiine_gx2/blob/master/udp_debug_reader/UdpDebugReader.exe running on your PC while running the DEBUG version of NUSspli on the Wii U. Make sure both are on the same network.

Hmm, well oddly enough the debug version works correctly, the problem only occurs with the non debug channel version. I can provide the log for it if it helps.

[1 (1).log](https://github.com/V10lator/NUSspli/files/6345940/1.1.log)

**Comment by V10lator** [comment]
Thanks and no need for the UDP log anymore. From the crashlog and your description that the debug verion behaves differently I expected this to be a memory issue, so I tried to port the I/O queue into a linux program and examine it with Valgrind. Result:
```
==166673== Thread 2:
==166673== Syscall param write(buf) points to uninitialised byte(s)
==166673==    at 0x499515F: __libc_write (write.c:26)
==166673==    by 0x499515F: write (write.c:24)
==166673==    by 0x4927634: _IO_file_write@@GLIBC_2.2.5 (fileops.c:1181)
==166673==    by 0x49269ED: new_do_write (fileops.c:449)
==166673==    by 0x4927CF5: _IO_new_file_xsputn (fileops.c:1255)
==166673==    by 0x4927CF5: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1197)
==166673==    by 0x491CE2B: fwrite (iofwrite.c:39)
==166673==    by 0x108D6A: executeIOQueue (ioThread.c:109)
==166673==    by 0x109045: ioThreadMain (ioThread.c:147)
==166673==    by 0x10970C: pthread_entry_point (thread.c:13)
==166673==    by 0x4893E15: start_thread (pthread_create.c:463)
==166673==    by 0x49A3E6E: clone (clone.S:95)
==166673==  Address 0x966a040 is 0 bytes inside a block of size 9,437,184 alloc'd
==166673==    at 0x483876F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==166673==    by 0x1091CF: initIOThread (ioThread.c:183)
==166673==    by 0x109843: main (main.c:10)
```
Note that ioThread.c is 1:1 what's in NUSspli, so the error has been tracked down to line 109. While that's a good thing I fail to see the buffer pointing to unaligned memory. Anyway, will try to track this down more further.

**Comment by V10lator** [comment]
Never mind, the above was a uninitialized buffer used for testing in the linux tool. Weirdly no more Valgrind errors afte fixing that. So this needs more investigation. :(

**Comment by V10lator** [comment]
@ChronosWing Are you downloading to SD or USB?

**Comment by ChronosWing** [comment]
> @ChronosWing Are you downloading to SD or USB?

USB.

**Comment by V10lator** [comment]
Please test one of these:
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.20-ALPHA4-Aroma.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.20-ALPHA4-Channel.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.20-ALPHA4-HBL.zip

**Comment by V10lator** [comment]
Fixed with 1.20.
